title: Project

columns:

  main:
    width: 2/3

    fields:
      description EN:
        type: textarea
        size: large

      description FR:
        type: textarea
        size: large

  sidebar:
    width: 1/3

    fields:
      images:
        type: files
        query: page.images
        size: small
