title: Project

columns:

  - width: 1/3
    fields:
      project_title:
        type: text

      images_covers:
        type: files
        query: page.images
        layout: cards
        size: tiny
        min: 1
        max: 1

      students:
        type: writer
        inline: false
        marks:
          - link
        nodes: false

      professors:
        type: writer
        inline: false
        marks:
          - link
        nodes: false

      assistants:
        type: writer
        inline: false
        marks:
          - link
        nodes: false

  - width: 2/3
      fields:

        description_EN:
          type: textarea
          size: large

        description_FR:
          type: textarea
          size: large

        info:
          label: ""
          type: info
          theme: none
          text: |
            ## Images or Vimeo links for project gallery
        images_gallery:
          label: images
          type: files
          query: page.images
          layout: cards
          size: tiny
        embed_items_gallery:
          label: code embed
          type: blocks
          fieldsets:
            - code
